/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as AdminIndexRouteImport } from './routes/_admin.index'
import { Route as AdminUsersRouteImport } from './routes/_admin.users'
import { Route as AdminSettingsRouteImport } from './routes/_admin.settings'
import { Route as AdminAnalyticsRouteImport } from './routes/_admin.analytics'
import { Route as AdminSubmissionsIndexRouteImport } from './routes/_admin.submissions.index'
import { Route as AdminProblemsIndexRouteImport } from './routes/_admin.problems.index'
import { Route as AdminContestsIndexRouteImport } from './routes/_admin.contests.index'
import { Route as AdminUsersIdRouteImport } from './routes/_admin.users_.$id'
import { Route as AdminSubmissionsIdRouteImport } from './routes/_admin.submissions.$id'
import { Route as AdminProblemsSyncRouteImport } from './routes/_admin.problems.sync'
import { Route as AdminProblemsCreateRouteImport } from './routes/_admin.problems.create'
import { Route as AdminProblemsIdRouteImport } from './routes/_admin.problems.$id'
import { Route as AdminContestsCreateRouteImport } from './routes/_admin.contests.create'
import { Route as AdminContestsIdRouteImport } from './routes/_admin.contests.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubmissionsIndexRoute = AdminSubmissionsIndexRouteImport.update({
  id: '/submissions/',
  path: '/submissions/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProblemsIndexRoute = AdminProblemsIndexRouteImport.update({
  id: '/problems/',
  path: '/problems/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContestsIndexRoute = AdminContestsIndexRouteImport.update({
  id: '/contests/',
  path: '/contests/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersIdRoute = AdminUsersIdRouteImport.update({
  id: '/users_/$id',
  path: '/users/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubmissionsIdRoute = AdminSubmissionsIdRouteImport.update({
  id: '/submissions/$id',
  path: '/submissions/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProblemsSyncRoute = AdminProblemsSyncRouteImport.update({
  id: '/problems/sync',
  path: '/problems/sync',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProblemsCreateRoute = AdminProblemsCreateRouteImport.update({
  id: '/problems/create',
  path: '/problems/create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProblemsIdRoute = AdminProblemsIdRouteImport.update({
  id: '/problems/$id',
  path: '/problems/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContestsCreateRoute = AdminContestsCreateRouteImport.update({
  id: '/contests/create',
  path: '/contests/create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContestsIdRoute = AdminContestsIdRouteImport.update({
  id: '/contests/$id',
  path: '/contests/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AdminIndexRoute
  '/login': typeof LoginRoute
  '/analytics': typeof AdminAnalyticsRoute
  '/settings': typeof AdminSettingsRoute
  '/users': typeof AdminUsersRoute
  '/contests/$id': typeof AdminContestsIdRoute
  '/contests/create': typeof AdminContestsCreateRoute
  '/problems/$id': typeof AdminProblemsIdRoute
  '/problems/create': typeof AdminProblemsCreateRoute
  '/problems/sync': typeof AdminProblemsSyncRoute
  '/submissions/$id': typeof AdminSubmissionsIdRoute
  '/users/$id': typeof AdminUsersIdRoute
  '/contests/': typeof AdminContestsIndexRoute
  '/problems/': typeof AdminProblemsIndexRoute
  '/submissions/': typeof AdminSubmissionsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/analytics': typeof AdminAnalyticsRoute
  '/settings': typeof AdminSettingsRoute
  '/users': typeof AdminUsersRoute
  '/': typeof AdminIndexRoute
  '/contests/$id': typeof AdminContestsIdRoute
  '/contests/create': typeof AdminContestsCreateRoute
  '/problems/$id': typeof AdminProblemsIdRoute
  '/problems/create': typeof AdminProblemsCreateRoute
  '/problems/sync': typeof AdminProblemsSyncRoute
  '/submissions/$id': typeof AdminSubmissionsIdRoute
  '/users/$id': typeof AdminUsersIdRoute
  '/contests': typeof AdminContestsIndexRoute
  '/problems': typeof AdminProblemsIndexRoute
  '/submissions': typeof AdminSubmissionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/_admin/analytics': typeof AdminAnalyticsRoute
  '/_admin/settings': typeof AdminSettingsRoute
  '/_admin/users': typeof AdminUsersRoute
  '/_admin/': typeof AdminIndexRoute
  '/_admin/contests/$id': typeof AdminContestsIdRoute
  '/_admin/contests/create': typeof AdminContestsCreateRoute
  '/_admin/problems/$id': typeof AdminProblemsIdRoute
  '/_admin/problems/create': typeof AdminProblemsCreateRoute
  '/_admin/problems/sync': typeof AdminProblemsSyncRoute
  '/_admin/submissions/$id': typeof AdminSubmissionsIdRoute
  '/_admin/users_/$id': typeof AdminUsersIdRoute
  '/_admin/contests/': typeof AdminContestsIndexRoute
  '/_admin/problems/': typeof AdminProblemsIndexRoute
  '/_admin/submissions/': typeof AdminSubmissionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/analytics'
    | '/settings'
    | '/users'
    | '/contests/$id'
    | '/contests/create'
    | '/problems/$id'
    | '/problems/create'
    | '/problems/sync'
    | '/submissions/$id'
    | '/users/$id'
    | '/contests/'
    | '/problems/'
    | '/submissions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/analytics'
    | '/settings'
    | '/users'
    | '/'
    | '/contests/$id'
    | '/contests/create'
    | '/problems/$id'
    | '/problems/create'
    | '/problems/sync'
    | '/submissions/$id'
    | '/users/$id'
    | '/contests'
    | '/problems'
    | '/submissions'
  id:
    | '__root__'
    | '/_admin'
    | '/login'
    | '/_admin/analytics'
    | '/_admin/settings'
    | '/_admin/users'
    | '/_admin/'
    | '/_admin/contests/$id'
    | '/_admin/contests/create'
    | '/_admin/problems/$id'
    | '/_admin/problems/create'
    | '/_admin/problems/sync'
    | '/_admin/submissions/$id'
    | '/_admin/users_/$id'
    | '/_admin/contests/'
    | '/_admin/problems/'
    | '/_admin/submissions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/': {
      id: '/_admin/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/users': {
      id: '/_admin/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/settings': {
      id: '/_admin/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/analytics': {
      id: '/_admin/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/submissions/': {
      id: '/_admin/submissions/'
      path: '/submissions'
      fullPath: '/submissions/'
      preLoaderRoute: typeof AdminSubmissionsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/problems/': {
      id: '/_admin/problems/'
      path: '/problems'
      fullPath: '/problems/'
      preLoaderRoute: typeof AdminProblemsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/contests/': {
      id: '/_admin/contests/'
      path: '/contests'
      fullPath: '/contests/'
      preLoaderRoute: typeof AdminContestsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/users_/$id': {
      id: '/_admin/users_/$id'
      path: '/users/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof AdminUsersIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/submissions/$id': {
      id: '/_admin/submissions/$id'
      path: '/submissions/$id'
      fullPath: '/submissions/$id'
      preLoaderRoute: typeof AdminSubmissionsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/problems/sync': {
      id: '/_admin/problems/sync'
      path: '/problems/sync'
      fullPath: '/problems/sync'
      preLoaderRoute: typeof AdminProblemsSyncRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/problems/create': {
      id: '/_admin/problems/create'
      path: '/problems/create'
      fullPath: '/problems/create'
      preLoaderRoute: typeof AdminProblemsCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/problems/$id': {
      id: '/_admin/problems/$id'
      path: '/problems/$id'
      fullPath: '/problems/$id'
      preLoaderRoute: typeof AdminProblemsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/contests/create': {
      id: '/_admin/contests/create'
      path: '/contests/create'
      fullPath: '/contests/create'
      preLoaderRoute: typeof AdminContestsCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/contests/$id': {
      id: '/_admin/contests/$id'
      path: '/contests/$id'
      fullPath: '/contests/$id'
      preLoaderRoute: typeof AdminContestsIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminContestsIdRoute: typeof AdminContestsIdRoute
  AdminContestsCreateRoute: typeof AdminContestsCreateRoute
  AdminProblemsIdRoute: typeof AdminProblemsIdRoute
  AdminProblemsCreateRoute: typeof AdminProblemsCreateRoute
  AdminProblemsSyncRoute: typeof AdminProblemsSyncRoute
  AdminSubmissionsIdRoute: typeof AdminSubmissionsIdRoute
  AdminUsersIdRoute: typeof AdminUsersIdRoute
  AdminContestsIndexRoute: typeof AdminContestsIndexRoute
  AdminProblemsIndexRoute: typeof AdminProblemsIndexRoute
  AdminSubmissionsIndexRoute: typeof AdminSubmissionsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminContestsIdRoute: AdminContestsIdRoute,
  AdminContestsCreateRoute: AdminContestsCreateRoute,
  AdminProblemsIdRoute: AdminProblemsIdRoute,
  AdminProblemsCreateRoute: AdminProblemsCreateRoute,
  AdminProblemsSyncRoute: AdminProblemsSyncRoute,
  AdminSubmissionsIdRoute: AdminSubmissionsIdRoute,
  AdminUsersIdRoute: AdminUsersIdRoute,
  AdminContestsIndexRoute: AdminContestsIndexRoute,
  AdminProblemsIndexRoute: AdminProblemsIndexRoute,
  AdminSubmissionsIndexRoute: AdminSubmissionsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
